"""NikitaDailyPlan ORM model — Spec 215 PR 215-A foundation.

The Heartbeat Engine persists Nikita's LLM-generated daily emotional arc per
user. The /tasks/heartbeat handler reads today's plan to drive proactive
touchpoints; the /tasks/generate-daily-arcs handler upserts a fresh plan each
morning at 5 AM UTC.

Table: nikita_daily_plan
Primary Key: id (UUID, gen_random_uuid())
Idempotency: UNIQUE (user_id, plan_date) — see migration
RLS: user-scoped read; service-role bypass for cron writes (see migration)

asyncpg JSONB strategy (CRITICAL — do not break):
    This module relies on SQLAlchemy's native dict↔JSONB mapping via
    ``Mapped[dict] + mapped_column(JSONB)``. The repository upserts ``arc_json``
    as a Python dict directly. **Do NOT call json.dumps() on arc_json before
    assignment** — that produces double-encoded jsonb (jsonb_typeof returns
    'string' instead of 'object') and downstream code breaks at the first
    field access.

    This is the PR #319 burn class: GH #318 stored ``{"age": "28"}`` instead
    of ``{"age": 28}`` because ``cast(json.dumps(value), JSONB)`` was applied
    before the asyncpg JSONB codec ran. The fix was to remove the json.dumps
    call. See ``test_heartbeat_repository_integration.py::test_arc_json_stores_native_dict_not_string``
    for the regression guard.

Phase 1 schema acknowledgment (Plan v4 R7):
    The ``arc_json`` column holds a discrete plan-step list (6-12 timestamped
    intentions) for Phase 1. Phase 2 introduces a parallel
    ``nikita_daily_intensity_state`` table for the continuous-distribution
    model (von Mises × Hawkes); this Phase 1 schema is intentionally
    throwaway-compatible and will not be extended by Phase 2.
"""

from datetime import date, datetime
from typing import Any
from uuid import UUID

from sqlalchemy import Date, DateTime, ForeignKey, Text, func
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column

from nikita.db.models.base import Base


class NikitaDailyPlan(Base):
    """Daily emotional arc for a single user (Spec 215 FR-001/FR-002).

    Generated by the LLM-driven planner (``nikita.heartbeat.planner``) and
    consumed by the /tasks/heartbeat handler. One row per (user_id, plan_date);
    upserts replace the row in place.

    Phase 1 fields (locked):
        id              UUID PK (gen_random_uuid())
        user_id         FK users.id ON DELETE CASCADE
        plan_date       date the arc applies to (UTC)
        arc_json        structured plan steps + conditional actions
        narrative_text  human-readable narrative for prompt injection
        generated_at    UTC timestamp of last upsert
        model_used      model ID (e.g. "claude-haiku-4-5-20251001")
    """

    __tablename__ = "nikita_daily_plan"

    id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        primary_key=True,
        server_default=func.gen_random_uuid(),
    )

    # FK to public.users(id) with ON DELETE CASCADE — when a user is deleted,
    # their cached plans go with them (no orphan rows).
    user_id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
    )

    # Date this plan applies to. Migration enforces a CHECK constraint
    # restricting plan_date to [2020-01-01, CURRENT_DATE + 14 days] to catch
    # clock-skew bugs and accidental backfills of the distant past. The +14d
    # upper bound allows Phase 2 backfill scenarios (today + 7-14 days) and
    # tolerates Cloud Run UTC vs Postgres UTC clock skew at the boundary.
    plan_date: Mapped[date] = mapped_column(Date, nullable=False)

    # Structured arc steps + conditional actions. See planner.py for the
    # Pydantic schema (DailyArc / ArcStep / ArcAction). The ``Mapped[dict]``
    # type adapter handles serialization end-to-end. Do NOT call json.dumps()
    # on this field — see module docstring for the PR #319 burn precedent.
    arc_json: Mapped[dict[str, Any]] = mapped_column(
        JSONB,
        nullable=False,
    )

    # Human-readable narrative for prompt injection. Phase 1 stores BOTH this
    # text form and the structured ``arc_json`` per OD2 (BOTH plan forms);
    # Phase 2 may unify or specialize.
    narrative_text: Mapped[str] = mapped_column(Text, nullable=False)

    # UTC timestamp of last upsert. The /tasks/generate-daily-arcs handler
    # uses this for cost-attribution queries (see idx_nikita_daily_plan_generated_at).
    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )

    # LLM model identifier for observability + cost-tracking. Nullable so that
    # synthetic test fixtures don't have to pretend an LLM was called.
    model_used: Mapped[str | None] = mapped_column(Text, nullable=True)

    def __repr__(self) -> str:
        return (
            f"NikitaDailyPlan("
            f"id={self.id!r}, "
            f"user_id={self.user_id!r}, "
            f"plan_date={self.plan_date!r}, "
            f"model_used={self.model_used!r})"
        )
