"""User Social Circle Model (Spec 035; Spec 055 Enhanced).

Stores personalized social circle generated during onboarding.
Each user has 5-8 named friend characters adapted to their profile.

Spec 055 additions:
- last_event: Timestamp of most recent life event referencing this NPC
- sentiment: Current sentiment toward/from this NPC (positive/negative/neutral/mixed)
"""

from datetime import UTC, datetime
from typing import TYPE_CHECKING, Any
from uuid import UUID, uuid4

from sqlalchemy import Boolean, DateTime, ForeignKey, Integer, String, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID as PGUUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from nikita.db.models.base import Base

if TYPE_CHECKING:
    from nikita.db.models.user import User


class UserSocialCircle(Base):
    """A friend character in Nikita's social circle for a specific user.

    Generated by SocialCircleGenerator during onboarding handoff.
    Characters are adapted based on user's location, hobbies, job, and meeting context.
    """

    __tablename__ = "user_social_circles"

    id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True), primary_key=True, default=uuid4
    )
    user_id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    friend_name: Mapped[str] = mapped_column(String(100), nullable=False)
    friend_role: Mapped[str] = mapped_column(String(50), nullable=False)
    age: Mapped[int | None] = mapped_column(Integer, nullable=True)
    occupation: Mapped[str | None] = mapped_column(String(100), nullable=True)
    personality: Mapped[str | None] = mapped_column(Text, nullable=True)
    relationship_to_nikita: Mapped[str | None] = mapped_column(Text, nullable=True)
    storyline_potential: Mapped[list[str]] = mapped_column(
        JSONB, nullable=False, default=list
    )
    trigger_conditions: Mapped[list[str]] = mapped_column(
        JSONB, nullable=False, default=list
    )
    adapted_traits: Mapped[dict[str, Any]] = mapped_column(
        JSONB, nullable=False, default=dict
    )
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)

    # Spec 055: NPC state tracking
    last_event: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    sentiment: Mapped[str | None] = mapped_column(
        String(20), default="neutral", nullable=True
    )

    created_at: Mapped[datetime] = mapped_column(
        default=lambda: datetime.now(UTC), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        default=lambda: datetime.now(UTC),
        onupdate=lambda: datetime.now(UTC),
        nullable=False,
    )

    # Relationship to User
    user: Mapped["User"] = relationship("User", back_populates="social_circle")

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary for context loading."""
        return {
            "name": self.friend_name,
            "role": self.friend_role,
            "age": self.age,
            "occupation": self.occupation,
            "personality": self.personality,
            "relationship": self.relationship_to_nikita,
            "storyline_potential": self.storyline_potential,
            "trigger_conditions": self.trigger_conditions,
            "adapted_traits": self.adapted_traits,
            "last_event": self.last_event.isoformat() if self.last_event else None,
            "sentiment": self.sentiment,
        }

    def __repr__(self) -> str:
        return f"<UserSocialCircle {self.friend_name} ({self.friend_role}) for user {self.user_id}>"
