import { existsSync, writeFileSync } from "node:fs"
import { resolve } from "node:path"

/**
 * Spec 216-G — Playwright global env setup.
 *
 * Writes `.env.local` with dummy NEXT_PUBLIC_* values BEFORE the dev server
 * starts. Required because:
 *   1. `lib/env.ts` throws fail-fast at SSR module load if any
 *      NEXT_PUBLIC_* required var is missing.
 *   2. Next.js 16 Turbopack spawns SSR workers that do NOT inherit
 *      process.env from the parent dev server reliably, so
 *      `webServer.env` and `process.env.X ??=` defaults in
 *      playwright.config.ts are not sufficient on their own.
 *   3. Next.js auto-loads `.env.local` at startup, which IS read into
 *      the Turbopack worker correctly.
 *
 * Only writes if the file does not exist (preserves real local dev env).
 */
async function globalSetup(): Promise<void> {
  const envPath = resolve(__dirname, "..", ".env.local")
  if (existsSync(envPath)) {
    return
  }
  const dummyEnv = [
    "# Auto-generated by portal/e2e/global-env-setup.ts for E2E CI.",
    "# Real local-dev values should override (do NOT commit this file).",
    "NEXT_PUBLIC_SUPABASE_URL=https://example.supabase.co",
    "NEXT_PUBLIC_SUPABASE_ANON_KEY=dummy-key-for-e2e",
    "NEXT_PUBLIC_API_URL=https://example.run.app",
    "NEXT_PUBLIC_TELEGRAM_BOT_USERNAME=Nikita_my_bot",
    "E2E_AUTH_BYPASS=true",
    "E2E_AUTH_ROLE=player",
    "",
  ].join("\n")
  writeFileSync(envPath, dummyEnv, { encoding: "utf-8" })
}

export default globalSetup
