import { existsSync, writeFileSync } from "node:fs"
import { resolve } from "node:path"
import { defineConfig, devices } from "@playwright/test"

// Spec 216-G — ensure NEXT_PUBLIC_* fail-fast env vars (lib/env.ts) are
// readable by Next.js Turbopack at dev-server startup. Required because:
//   1. lib/env.ts throws fail-fast at SSR module load if any
//      NEXT_PUBLIC_* required var is missing.
//   2. Next.js 16 Turbopack spawns SSR workers that do NOT reliably
//      inherit process.env from the parent dev server, so
//      `webServer.env` alone is insufficient.
//   3. Next.js auto-loads `.env.local` at startup, which IS read into
//      the Turbopack worker correctly.
//   4. Playwright globalSetup runs AFTER webServer starts, too late
//      to influence SSR module-load. Must write the file here at
//      config-load time before defineConfig() returns.
//
// Skips when .env.local already exists (preserves real local-dev env).
const envLocalPath = resolve(__dirname, ".env.local")
if (!existsSync(envLocalPath)) {
  const dummyEnv = [
    "# Auto-generated by playwright.config.ts for E2E CI.",
    "# Real local-dev values should override (do NOT commit this file).",
    "NEXT_PUBLIC_SUPABASE_URL=https://example.supabase.co",
    "NEXT_PUBLIC_SUPABASE_ANON_KEY=dummy-key-for-e2e",
    "NEXT_PUBLIC_API_URL=https://example.run.app",
    "NEXT_PUBLIC_TELEGRAM_BOT_USERNAME=Nikita_my_bot",
    "E2E_AUTH_BYPASS=true",
    "E2E_AUTH_ROLE=player",
    "",
  ].join("\n")
  writeFileSync(envLocalPath, dummyEnv, { encoding: "utf-8" })
}

// Belt-and-suspenders: also seed process.env for the playwright runner itself.
process.env.NEXT_PUBLIC_SUPABASE_URL ??= "https://example.supabase.co"
process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ??= "dummy-key-for-e2e"
process.env.NEXT_PUBLIC_API_URL ??= "https://example.run.app"
process.env.NEXT_PUBLIC_TELEGRAM_BOT_USERNAME ??= "Nikita_my_bot"

const PORT = 3003

export default defineConfig({
  testDir: "./e2e",
  fullyParallel: false,
  forbidOnly: !!process.env.CI,
  retries: 1,
  workers: 1,
  reporter: [["html", { open: "never" }], ["list"]],
  timeout: 60_000,
  use: {
    baseURL: `http://localhost:${PORT}`,
    trace: "on-first-retry",
    screenshot: "only-on-failure",
    colorScheme: "dark",
    navigationTimeout: 30_000,
  },
  projects: [
    {
      name: "player",
      testMatch: /^(?!.*admin).*\.spec\.ts$/,
      use: { ...devices["Desktop Chrome"], viewport: { width: 1280, height: 720 } },
    },
    {
      name: "admin",
      testMatch: /admin.*\.spec\.ts$/,
      use: { ...devices["Desktop Chrome"], viewport: { width: 1280, height: 720 } },
    },
  ],
  webServer: {
    command: `npm run dev -- --port ${PORT}`,
    url: `http://localhost:${PORT}`,
    reuseExistingServer: !process.env.CI,
    timeout: 60_000,
    env: {
      E2E_AUTH_BYPASS: "true",
      E2E_AUTH_ROLE: "player",
      NEXT_PUBLIC_SUPABASE_URL: "https://example.supabase.co",
      NEXT_PUBLIC_SUPABASE_ANON_KEY: "dummy-key-for-e2e",
      NEXT_PUBLIC_API_URL: "https://example.run.app",
      NEXT_PUBLIC_TELEGRAM_BOT_USERNAME: "Nikita_my_bot",
    },
  },
})
